
spring:

  # Color console
  output:
    ansi:
      enabled: always

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssp?serverTimezone=UTC&characterEncoding=UTF-8
    username: dogyun
    password: 1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: create    # 서버 재 실행 시 DB를 초기화 / update : 초기화하지 않음.

    generate-ddl: false
    show-sql: true        # 실행되는 쿼리문을 보여줌
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true